Internal error: 'with' clause failed unexpectedly in 'main'
	"test15"
	with_1_1 <==
	main_0_0
